config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  
  devise_for :users,controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "walls/posts#index"

  resources :messages

  resources :clubs do
    resources :posts, module: :clubs do
      resources :comments, only: [:new, :create, :destroy]
    end
    resource :chatroom, as: "chat"
  end

  resource :wall do 
    resources :posts, module: :walls do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :memberships, only: [:create, :update, :destroy]

  #where does users index go?
  resources :users, only: [:edit, :update] do
    resource :profile, only: [:show, :edit, :update]
  end

  resources :chats, only: [:index, :show]

  resources :friend_requests, only: [:new, :create, :index, :destroy, :update]
  get "/friend_requests/search", to: "friend_requests#search", as: "search_users"

  #Like and unlike paths
  post "/posts/:id/like", to: "posts#like", as: "like_post" 
  delete "/posts/:id/like", to: "posts#unlike", as: "unlike_post"

  post "/posts/:post_id/comments/:id/like", to: "comments#like", as: "like_comment"
  delete "/posts/:post_id/comments/:id/like", to: "comments#unlike", as: "unlike_comment"

  resources :notifications, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord

    include ActiveModel::Validations
    validates_with ImageValidator
    
    validates :owner_id, presence: true
    validates :name, presence: true, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 10}

    #between 10 and 50 members, defines the maximum amount of members allowed in club (no minimum)
    validates :capacity, presence: true, numericality: {
        greater_than_or_equal_to: 10,
        less_than_or_equal_to: 50
    }

    #after created,
    after_create :create_chatroom

    #whenever club is saved, this will run (need to check sometime that this is working)
    validate :member_count_less_than_capacity, on: :edit

    belongs_to :owner, class_name: "User"

    #club image
    has_one_attached :image

    has_many :memberships, dependent: :destroy
    has_many :members, through: :memberships
    has_many :posts, as: :postable, dependent: :destroy

    has_one :chatroom, dependent: :destroy

    #Club Methods
    def unblocked_members
        unblocked_ids = Membership.where(club_id: self.id, blocked: false).pluck(:member_id)
        User.where(id: unblocked_ids)
    end

    def blocked_members
        blocked_ids = Membership.where(club_id: self.id, blocked: true).pluck(:member_id)
        User.where(id: blocked_ids)
    end

    def member_count
        #only count unblocked members
        self.unblocked_members.count
    end

    def member?(user_id)
        bool = (self.memberships.find_by(member_id: user_id))? true : false
    end

    def background_img
        img_path = (self.image.attached?)? self.image : "club_default.jpg"
    end

    private

    #ONLY RUN THIS IF EDITING CLUB!
    def member_count_less_than_capacity
        if (self.capacity).is_a?(Integer) && self.member_count > self.capacity 
            errors.add(:capacity, "Capacity cannot be lower than the total number of current members.")
        end
    end

    def create_chatroom
        Chatroom.create(club: self)
    end
end

app/models/post.rb
class Post < ApplicationRecord
    
    include ActiveModel::Validations
    validates_with ImageValidator

    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true, length: {minimum: 10}

    belongs_to :user
    #make post polymorphic! (can belong to either wall or club)
    belongs_to :postable, polymorphic: true

    has_one_attached :image

    has_many :comments, dependent: :destroy
    has_many :likes, :as => :likeable, dependent: :destroy

    #make sure a user can only like ONCE on a post
    def liked?(user)
        self.likes.find{|like| like.user_id == user.id}
    end

    def date
        self.created_at.strftime("%d-%m-%Y %H:%M")
    end
end

app/controllers/clubs/comments_controller.rb
class Clubs::CommentsController < CommentsController
end

app/controllers/clubs/posts_controller.rb
class Clubs::PostsController < PostsController
    #make sure later that check member ALWAYS runs before check_blocked, or it will error why does prepend_before_action result error?
    before_action :check_member 
    before_action :check_blocked

    def index
        #maybe all posts, from UNBLOCEKD USERS only?
        @club = Club.find(params[:club_id])
        @posts = Post.where(postable_type: "Club", postable_id: params[:club_id]).order('created_at DESC')
    end

    private

    def check_blocked
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if (@membership.blocked == true)
            #add flash[:error] to club show page later
            flash[:alert] = "You are blocked from this club."
            redirect_to club_path(@membership.club_id)
        end
    end

    def check_member
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if @membership.nil?
            flash[:alert] = "You must be a member of this club"
            redirect_to @postable
        end
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    #need some kinda validation for show, only let members/owner view the club
    before_action :require_owner, only: [:edit, :update, :destroy]

    def index
        @clubs = Club.all
    end

    def show
        @club = Club.find(params[:id])
    end

    def new
        @club = Club.new
    end

    def create
        @club = current_user.owned_clubs.build(club_params)

        if @club.save
            flash[:alert] = "Club successfully created."
            #automatically create membership for owner
            Membership.create(member_id: current_user.id, club_id: @club.id)

            redirect_to @club
        else
            render :new
        end
    end

    def edit
        @club = Club.find(params[:id])
    end

    def update
        @club = Club.find(params[:id])

        if @club.update(club_params)
            flash[:alert] = "Club succesfully saved."
            redirect_to @club
        else
            render :edit
        end
    end

    def destroy
        @club = Club.find(params[:id])
        # @post.image.purge
        @club.destroy
        flash[:alert] = "Club succesfully destroyed."

        redirect_to clubs_path
    end

    private

    def club_params
        params.require(:club).permit(:owner_id, :name, :description, :capacity, :image)
    end

    def require_owner
        #might be redundant
        @club = Club.find(params[:id])
        unless (current_user.id == @club.owner_id)
            flash[:alert] = "You do not have permission to perform this action."
            redirect_to @club
        end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    prepend_before_action :load_postable, except: [:like, :unlike]
    prepend_before_action :load_postable_for_like, only: [:like, :unlike]

    before_action :require_owner, only: [:edit, :update, :destroy]
    
    def show
        @post = Post.find(params[:id])
        #generate new comment obj, for "new comment form" in post#show
        @comment = @post.comments.new


        #adjust club template to use show_owned and unowned template. 
        if @post.user == current_user
            render :show_owned
        else
            render :show_unowned
        end
    end

    def new
        @post = @postable.posts.new
    end

    def create
        @post = @postable.posts.build(post_params)
        @post.user = current_user

        if @post.save
            flash[:alert] = "Post successfully created."
            redirect_to [@postable_name, :posts]
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            flash[:alert] = "Post succesfully saved."
            redirect_to [@postable_name, @post]
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.image.purge
        @post.destroy

        redirect_to [@postable_name, :posts]
    end

    def like
        Like.create(user_id: current_user.id, likeable_id: @post.id, likeable_type: "Post")
        redirect_to [@postable_name, @post]
    end

    def unlike  
        Like.find_by(likeable_id: @post.id, user_id: current_user.id, likeable_type: "Post").destroy
        redirect_to [@postable_name, @post]
    end

    protected

    def post_params
        params.require(:post).permit(:title, :body, :image)
    end

    def load_postable
        resource, id = request.path.split("/")[1,2]
        @postable = resource.singularize.classify.constantize.find(id)
        #specifically for routes.
        @postable_name = @postable
    end

    def load_postable_for_like
        #singular (ONLY wall/posts) and plural (clubs/1/posts) routes handled here, because all types of post likes will route to post#like
        @post = Post.find(params[:id])
        @postable = @post.postable_type.classify.constantize.find(@post.postable_id)
        @postable_name = (@postable.class == Wall)? "wall" : @postable 
    end

    def require_owner
        @post = Post.find(params[:id])
        unless (current_user.id == @post.user_id)
            #make into flash[:error] later
            flash[:alert] = "You do not have the permission to edit this post"
            redirect_to [@postable_name, @post]
        end
    end
end

app/controllers/walls/posts_controller.rb
class Walls::PostsController < PostsController
    #overwrite @postable
    prepend_before_action :load_postable

    def index
        @posts = Post.where(postable_type: "Wall").order("created_at DESC")
    end

    private

    def load_postable
        @postable = Wall.first
        @postable_name = "wall"
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/clubs/posts/edit.html.erb
<%=render "posts/post_form", form_title: "Edit Club Post"%>

app/views/clubs/posts/index.html.erb
<div class="w-100 d-flex justify-content-center">
    <%# need to add button for adding posts %>

    <div id="club-plus-button">
        <%=link_to "", new_club_post_path(@club), class: "link" %>
        <img class="" src="<%=asset_path("icons8-plus-96.png")%>">      
    </div>


    <div id="main-posts" class="d-flex flex-column align-items-center">
        <%@posts.each do |post|%>
            <div class="post d-flex flex-column bg-white shadow-sm mb-4 p-3">

                <div class="author-info d-flex">
                    <div class="square-frame">
                        <img class="" src="<%=asset_path(url_for(post.user.profile.attached_img))%>">
                    </div>
                    <div class="d-flex flex-column mx-2">
                        <%=link_to "#{post.user.name}", user_profile_path(post.user), class: "profile-link"%>
                        <p class="date m-0"><%=local_time_ago(post.created_at) %></p>
                    </div>
                </div>

                <div class="post-text my-3">
                    <p class="title mb-1"><%=post.title%></p>
                    <p class="body m-0"><%=post.body%></p>
                </div>

                <% if post.image.attached?%>
                    <img class="post-pic" src= "<%=asset_path(url_for(post.image))%>">
                <%end%>
            
                
                <div class="bottom-bar d-flex justify-content-between mt-3">
                    <div class="d-flex">
                        <div class="likes d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi like-icon bi-hand-thumbs-up" viewBox="0 0 16 16">
                                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                            </svg>
                            <p class="my-0 mx-1"><%=post.likes.count%></p>
                        </div>

                        <div class="comments d-flex align-items-center mx-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-right" viewBox="0 0 16 16">
                                <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                            </svg>
                            <p class="my-0 mx-2"><%=post.comments.count%></p>
                        </div>
                    </div>
                        
                    <%=link_to "View more", wall_post_path(post)%>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/clubs/posts/new.html.erb
<%=render "posts/post_form", form_title: "New Club Post"%>

app/views/clubs/posts/show.html.erb
<%# <%=link_to "Back", [@postable_name, :posts]%> 

<div id="post-container" class="d-flex justify-content-center">
    <p>POST</p>

    <div class="post bg-light d-flex flex-column p-3 shadow-sm">
        <h2 class=""><%=@post.title%></h2>

        <%if @post.image.attached?%>
            <img class="post-img w-100" src="<%=asset_path(url_for(@post.image))%>">
        <%end%>

        <div>
            <p class="my-2"><%=@post.body%></p>
            <p class="">Likes: <%=@post.likes.count%></p>
        </div>

        <%if current_user.id == @post.user_id%>
            <div class="links">
            <%# postable_name, so that it works for both wall and other postable models %>
                <%=link_to "Edit", [:edit, @postable_name, @post]%>
                <%=link_to "Delete", [@postable_name, @post], method: :delete%>
            </div>
        <%else%>
            <%if @post.liked?(current_user) %>
                <%=button_to "Unlike", unlike_post_path, method: :delete, class: "btn btn-light border" %>
            <%else%>
                <%=button_to "Like", like_post_path, method: :post, class: "btn btn-light border"%>
            <%end%>
        <%end%>

        <%=render "comments/comment_form", comment: @comment, route: club_post_comments_path(@postable, @post)%>
        <%=render partial: "comments/comment_section", locals: {post_id: @post.id} %>
    </div>
</div>


<%# liking a post automatically likes your own comment on a post also unlikes comment on post?? %>

app/views/clubs/posts/show_owned.html.erb
<div id="post-container" class="d-flex justify-content-center">
    <div class="post bg-light d-flex flex-column p-3 shadow-sm">
        <div class="d-flex justify-content-between">
            <div class="author-info d-flex mb-3">
                <%@user = @post.user%>
                <div class="square-frame">
                    <img class="" src="<%=asset_path(url_for(@user.profile.attached_img))%>">
                </div>
                <div class="d-flex flex-column mx-2">
                    <%=link_to "#{@user.name}", user_profile_path(@user), class: "profile-link"%>
                    <p class="date m-0"><%=local_time(@post.created_at, "%d-%m-%Y %H:%M") %></p>
                </div>
            </div>

            <div class="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" data-bs-toggle="dropdown" aria-expanded="false" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                    <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><%=link_to "Edit", edit_wall_post_path(@post), class: "dropdown-item"%></li>
                    <li><%=link_to "Delete", wall_post_path(@post), method: :delete, data: {confirm: "Are you sure? This action cannot be reversed"}, class: "dropdown-item"%></li>
                </ul>
            </div>
        </div>

        <div>
            <h3 class="mt-2"><%=@post.title%></h3>
            <p class="mt-2 mb-4 body"><%=@post.body%></p>
        </div>

        <%if @post.image.attached?%>
            <img class="post-img w-100" src="<%=asset_path(url_for(@post.image))%>">
        <%end%>

        <div class="likes d-flex align-items-center mt-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi like-icon bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg>
            <p class="my-0 mx-1"><%=@post.likes.count%></p>
        </div>

    
        <div class="comments-section mt-4">
            <%=render "comments/comment_form", comment: @comment, route: wall_post_comments_path(@post)%>
            <%=render partial: "comments/comment_section", locals: {post_id: @post.id} %>
        </div>
    </div>
</div>

app/views/clubs/posts/show_unowned.html.erb
<div id="post-container" class="d-flex justify-content-center">
    <div class="post bg-light d-flex flex-column p-3 shadow-sm">

        <div class="d-flex justify-content-between">
            <div class="author-info d-flex mb-3">
                <%@user = @post.user%>
                <div class="square-frame">
                    <img class="" src="<%=asset_path(url_for(@user.profile.attached_img))%>">
                </div>
                <div class="d-flex flex-column mx-2">
                    <%=link_to "#{@user.name}", user_profile_path(@user), class: "profile-link"%>
                    <p class="date m-0"><%=local_time(@post.created_at, "%d-%m-%Y %H:%M") %></p>
                </div>
            </div>
        </div>

        <div>
            <h3 class="mt-2"><%=@post.title%></h3>
            <p class="mt-2 mb-4 body"><%=@post.body%></p>
        </div>

        <%if @post.image.attached?%>
            <img class="post-img w-100" src="<%=asset_path(url_for(@post.image))%>">
        <%end%>


        <div class="d-flex align-items-center mt-2">
            <%if @post.liked?(current_user) %>
                <%=link_to unlike_post_path, method: :delete, class: "btn border" do%>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                        <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                    </svg>
                <%end%>
            <%else%>
                <%=link_to like_post_path, method: :post, class: "btn border" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi like-icon bi-hand-thumbs-up" viewBox="0 0 16 16">
                        <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                    </svg>
                <%end%>
            <%end%>
            <p class="my-0 mx-1"><%=@post.likes.count%></p>
        </div>
        

        <div class="comments-section mt-4">
            <%=render "comments/comment_form", comment: @comment, route: wall_post_comments_path(@post)%>
            <%=render partial: "comments/comment_section", locals: {post_id: @post.id} %>
        </div>
    </div>
</div>