config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  
  devise_for :users,controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "walls/posts#index"

  resources :messages

  resources :clubs do
    resources :posts, module: :clubs do
      resources :comments, only: [:new, :create, :destroy]
    end
    resource :chatroom, as: "chat"
  end

  resource :wall do 
    resources :posts, module: :walls do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :memberships, only: [:create, :update, :destroy]

  #where does users index go?
  resources :users, only: [:edit, :update] do
    resource :profile, only: [:show, :edit, :update]
  end

  resources :chats, only: [:index, :show]

  resources :friend_requests, only: [:new, :create, :index, :destroy, :update]
  get "/friend_requests/search", to: "friend_requests#search", as: "search_users"

  #Like and unlike paths
  post "/posts/:id/like", to: "posts#like", as: "like_post" 
  delete "/posts/:id/like", to: "posts#unlike", as: "unlike_post"

  post "/posts/:post_id/comments/:id/like", to: "comments#like", as: "like_comment"
  delete "/posts/:post_id/comments/:id/like", to: "comments#unlike", as: "unlike_comment"

  resources :notifications, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    
    include ActiveModel::Validations
    validates_with ImageValidator

    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true, length: {minimum: 10}

    belongs_to :user
    #make post polymorphic! (can belong to either wall or club)
    belongs_to :postable, polymorphic: true

    has_one_attached :image

    has_many :comments, dependent: :destroy
    has_many :likes, :as => :likeable, dependent: :destroy

    #make sure a user can only like ONCE on a post
    def liked?(user)
        self.likes.find{|like| like.user_id == user.id}
    end

    def date
        self.created_at.strftime("%d-%m-%Y %H:%M")
    end
end

app/models/wall.rb
class Wall < ApplicationRecord
    validate :check_record, on: :create
    has_many :posts, as: :postable
    
    def check_record
        if Wall.all.count > 0
            errors.add(:base, :invalid, "There can only be one wall model instance")
        end
    end
end

app/controllers/clubs/posts_controller.rb
class Clubs::PostsController < PostsController
    #make sure later that check member ALWAYS runs before check_blocked, or it will error why does prepend_before_action result error?
    before_action :check_member 
    before_action :check_blocked

    def index
        #maybe all posts, from UNBLOCEKD USERS only?
        @club = Club.find(params[:club_id])
        @posts = Post.where(postable_type: "Club", postable_id: params[:club_id]).order('created_at DESC')
    end

    private

    def check_blocked
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if (@membership.blocked == true)
            #add flash[:error] to club show page later
            flash[:alert] = "You are blocked from this club."
            redirect_to club_path(@membership.club_id)
        end
    end

    def check_member
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if @membership.nil?
            flash[:alert] = "You must be a member of this club"
            redirect_to @postable
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    prepend_before_action :load_postable, except: [:like, :unlike]
    prepend_before_action :load_postable_for_like, only: [:like, :unlike]

    before_action :require_owner, only: [:edit, :update, :destroy]
    
    def show
        @post = Post.find(params[:id])
        #generate new comment obj, for "new comment form" in post#show
        @comment = @post.comments.new


        #adjust club template to use show_owned and unowned template. 
        if @post.user == current_user
            render :show_owned
        else
            render :show_unowned
        end
    end

    def new
        @post = @postable.posts.new
    end

    def create
        @post = @postable.posts.build(post_params)
        @post.user = current_user

        if @post.save
            flash[:alert] = "Post successfully created."
            redirect_to [@postable_name, :posts]
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            flash[:alert] = "Post succesfully saved."
            redirect_to [@postable_name, @post]
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.image.purge
        @post.destroy

        redirect_to [@postable_name, :posts]
    end

    def like
        Like.create(user_id: current_user.id, likeable_id: @post.id, likeable_type: "Post")
        redirect_to [@postable_name, @post]
    end

    def unlike  
        Like.find_by(likeable_id: @post.id, user_id: current_user.id, likeable_type: "Post").destroy
        redirect_to [@postable_name, @post]
    end

    protected

    def post_params
        params.require(:post).permit(:title, :body, :image)
    end

    def load_postable
        resource, id = request.path.split("/")[1,2]
        @postable = resource.singularize.classify.constantize.find(id)
        #specifically for routes.
        @postable_name = @postable
    end

    def load_postable_for_like
        #singular (ONLY wall/posts) and plural (clubs/1/posts) routes handled here, because all types of post likes will route to post#like
        @post = Post.find(params[:id])
        @postable = @post.postable_type.classify.constantize.find(@post.postable_id)
        @postable_name = (@postable.class == Wall)? "wall" : @postable 
    end

    def require_owner
        @post = Post.find(params[:id])
        unless (current_user.id == @post.user_id)
            #make into flash[:error] later
            flash[:alert] = "You do not have the permission to edit this post"
            redirect_to [@postable_name, @post]
        end
    end
end

app/controllers/walls/comments_controller.rb
class Walls::CommentsController < CommentsController
    before_action :load_postable

    private

    def load_postable
        post_id = request.path.split("/")[3]
        @post = Post.find(post_id)
        @postable_name = "wall"
    end
end

app/controllers/walls/posts_controller.rb
class Walls::PostsController < PostsController
    #overwrite @postable
    prepend_before_action :load_postable

    def index
        @posts = Post.where(postable_type: "Wall").order("created_at DESC")
    end

    private

    def load_postable
        @postable = Wall.first
        @postable_name = "wall"
    end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
    def index
        #this will be the homepage
        #later restrict to just wall posts
        @posts = Post.all
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/walls/posts/edit.html.erb
<%=form_with model: @post, url: wall_post_path(@post.id) do |form|%>
    <%# same content as _post_form partial %>

    <div class="form-container my-4 p-3 bg-light">
        <h2>Edit Wall Post</h2>

        <div class="post-errors">
            <%unless @post.errors.messages.empty?%>
                <div class="alert alert-danger">
                    <%@post.errors.full_messages.each do |msg|%>
                        <li><%=msg%></li>
                    <%end%>
                </div>
            <%end%>
        </div>

        <div class="form-group my-2">
            <%=form.label :title%>
            <%=form.text_field :title, class: "form-control"%>
        </div>

        <div class="form-group my-2">
            <%=form.label :body%>
            <%=form.text_area :body, class: "form-control body"%>
        </div>

        <div class="form-group my-2">
            <%=form.label :image%>
            <%=form.file_field :image, class: "file-field form-control", direct_upload: true%>
            <small class="form-text text-muted">(Optional)</small>
        </div>

        <%=form.submit "Submit", class:"submit-button w-100 text-white border p-2 mt-3"%>
    </div>
<%end%>

app/views/walls/posts/index.html.erb
<div id="homepage" class="d-flex justify-content-center">
    <div class="plus-button">
        <%=link_to "", new_wall_post_path, class: "link" %>
        <img class="" src="<%=asset_path("icons8-plus-96.png")%>">
    </div>

    <div id="main-posts" class="d-flex flex-column align-items-center">
        <%@posts.each do |post|%>
            <div class="post d-flex flex-column bg-white shadow-sm mb-4 p-3">

                <div class="author-info d-flex">
                    <div class="square-frame">
                        <img class="" src="<%=asset_path(url_for(post.user.profile.attached_img))%>">
                    </div>
                    <div class="d-flex flex-column mx-2">
                        <%=link_to "#{post.user.name}", user_profile_path(post.user), class: "profile-link"%>
                        <p class="date m-0"><%=local_time_ago(post.created_at) %></p>
                    </div>
                </div>

                <div class="post-text my-3">
                    <p class="title mb-1"><%=post.title%></p>
                    <p class="body m-0"><%=post.body%></p>
                </div>

                <%# dont forget to add restrictions to dimensions of img %>
                <% if post.image.attached?%>
                    <img class="post-pic" src= "<%=asset_path(url_for(post.image))%>">
                <%end%>
            
                
                <div class="bottom-bar d-flex justify-content-between mt-3">
                    <div class="d-flex">
                        <div class="likes d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi like-icon bi-hand-thumbs-up" viewBox="0 0 16 16">
                                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                            </svg>
                            <p class="my-0 mx-1"><%=post.likes.count%></p>
                        </div>

                        <div class="comments d-flex align-items-center mx-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-right" viewBox="0 0 16 16">
                                <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                            </svg>
                            <p class="my-0 mx-2"><%=post.comments.count%></p>
                        </div>
                    </div>
                        
                    <%=link_to "View more", wall_post_path(post)%>
                </div>
            </div>
        <%end%>
    </div>

    <div id="friend-column" class="d-flex flex-column justify-content-start">
        <p class="bg-light text-secondary border p-2 mb-1">Friends</p>
        <%current_user.friends.each do |friend|%>
            <%online_icon_class = (friend.status.online === true)? "isOnline" : "isOffline"%>

            <div class="friend-card bg-white d-flex my-1">
                
                <div class="square-frame">
                    <img class="" src="<%=asset_path(url_for(friend.profile.attached_img))%>">
                </div>

                <div class="d-flex flex-column mx-2 justify-content-center w-100">

                    <div class="d-flex justify-content-between align-items-center">
                        <%=link_to "#{friend.name}", user_profile_path(friend), class: "profile-link"%>
                        <div class="online-icon <%=online_icon_class%> ms-2 me-1" data-user-id="<%=friend.id%>"></div>
                    </div>

                    <div class="links">
                        <%=link_to "View profile", user_profile_path(friend)%>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/walls/posts/new.html.erb
<%= render "posts/post_form", form_title: "New Post"%>

app/views/walls/posts/show.html.erb
<%# currently unused %>

<div id="post-container" class="d-flex justify-content-center">
    <div class="post bg-light d-flex flex-column p-3 shadow-sm">
        <p><%=@postable_name%></p>
        <div class="d-flex justify-content-between">
            <div class="author-info d-flex mb-3">
                <%@user = @post.user%>
                <div class="square-frame">
                    <img class="" src="<%=asset_path(url_for(@user.profile.attached_img))%>">
                </div>
                <div class="d-flex flex-column mx-2">
                    <%=link_to "#{@user.name}", user_profile_path(@user), class: "profile-link"%>
                    <p class="date m-0"><%=local_time(@post.created_at, "%d-%m-%Y %H:%M") %></p>
                </div>
            </div>

            <%if current_user.id == @post.user_id%>
                <div class="dropdown">
                    <svg xmlns="http://www.w3.org/2000/svg" data-bs-toggle="dropdown" aria-expanded="false" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                    </svg>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><%=link_to "Edit", edit_wall_post_path(@post), class: "dropdown-item"%></li>
                        <li><%=link_to "Delete", wall_post_path(@post), method: :delete, data: {confirm: "Are you sure? This action cannot be reversed"}, class: "dropdown-item"%></li>
                    </ul>
                </div>
            <%end%>
        </div>

        <div>
            <h3 class="mt-2"><%=@post.title%></h3>
            <p class="mt-2 mb-4 body"><%=@post.body%></p>
        </div>

        <%if @post.image.attached?%>
            <img class="post-img w-100" src="<%=asset_path(url_for(@post.image))%>">
        <%end%>


        <div class="d-flex justify-content-between align-items-center mt-2">
            <p class="m-0">Likes: <%=@post.likes.count%></p>

            <%if current_user.id != @post.user_id%>
                <%if @post.liked?(current_user) %>
                    <%=button_to "Unlike", unlike_post_path, method: :delete, class: "btn btn-light border"%>
                <%else%>
                    <%=button_to "Like", like_post_path, method: :post, class: "btn btn-light border"%>
                <%end%>
            <%end%>
        </div>
        

        <div class="comments-section mt-4">
            <%=render "comments/comment_form", comment: @comment, route: wall_post_comments_path(@post)%>
            <%=render partial: "comments/comment_section", locals: {post_id: @post.id} %>
        </div>
    </div>
</div>

app/views/walls/posts/show_owned.html.erb
<div id="post-container" class="d-flex justify-content-center">
    <div class="post bg-light d-flex flex-column p-3 shadow-sm">
        <div class="d-flex justify-content-between">
            <div class="author-info d-flex mb-3">
                <%@user = @post.user%>
                <div class="square-frame">
                    <img class="" src="<%=asset_path(url_for(@user.profile.attached_img))%>">
                </div>
                <div class="d-flex flex-column mx-2">
                    <%=link_to "#{@user.name}", user_profile_path(@user), class: "profile-link"%>
                    <p class="date m-0"><%=local_time(@post.created_at, "%d-%m-%Y %H:%M") %></p>
                </div>
            </div>

            <div class="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" data-bs-toggle="dropdown" aria-expanded="false" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                    <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><%=link_to "Edit", edit_wall_post_path(@post), class: "dropdown-item"%></li>
                    <li><%=link_to "Delete", wall_post_path(@post), method: :delete, data: {confirm: "Are you sure? This action cannot be reversed"}, class: "dropdown-item"%></li>
                </ul>
            </div>
        </div>

        <div>
            <h3 class="mt-2"><%=@post.title%></h3>
            <p class="mt-2 mb-4 body"><%=@post.body%></p>
        </div>

        <%if @post.image.attached?%>
            <img class="post-img w-100" src="<%=asset_path(url_for(@post.image))%>">
        <%end%>


        <%# nos tyling %>
        <div class="likes d-flex align-items-center mt-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi like-icon bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg>
            <p class="my-0 mx-2"><%=@post.likes.count%></p>
        </div>

    
        <div class="comments-section mt-4">
            <%=render "comments/comment_form", comment: @comment, route: wall_post_comments_path(@post)%>
            <%=render partial: "comments/comment_section", locals: {post_id: @post.id} %>
        </div>
    </div>
</div>