config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  
  devise_for :users,controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "walls/posts#index"

  resources :messages

  resources :clubs do
    resources :posts, module: :clubs do
      resources :comments, only: [:new, :create, :destroy]
    end
    resource :chatroom, as: "chat"
  end

  resource :wall do 
    resources :posts, module: :walls do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :memberships, only: [:create, :update, :destroy]

  #where does users index go?
  resources :users, only: [:edit, :update] do
    resource :profile, only: [:show, :edit, :update]
  end

  resources :chats, only: [:index, :show]

  resources :friend_requests, only: [:new, :create, :index, :destroy, :update]
  get "/friend_requests/search", to: "friend_requests#search", as: "search_users"

  #Like and unlike paths
  post "/posts/:id/like", to: "posts#like", as: "like_post" 
  delete "/posts/:id/like", to: "posts#unlike", as: "unlike_post"

  post "/posts/:post_id/comments/:id/like", to: "comments#like", as: "like_comment"
  delete "/posts/:post_id/comments/:id/like", to: "comments#unlike", as: "unlike_comment"

  resources :notifications, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
    #need to add validation to make sure combination of requester and reciever is unique

    belongs_to :requester, class_name: "User"
    belongs_to :reciever, class_name: "User"
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    #all possible people you can send requests to 
    def index
        @new_users = default_users(10)
        
        @pending_users = current_user.pending_invitees
        @invites_from = current_user.invites_from
    end

    def search
        #current user will not be returned as a result
        query = params[:query]
        
        #loads 10 users that aren't friends with current_user by default. 
        @users = default_users(10)

        if query != "" 
            @users = User.find_by_sql("SELECT * FROM users WHERE UPPER(name) LIKE UPPER('%#{query}%') AND id <> #{current_user.id}")
        end

        respond_to do |format|
            format.js {render layout: false}
        end
    end



    def create
        @request = current_user.sent_friend_requests.build(friend_request_params)

        if @request.save
            flash[:alert] = "Friend request sent!"
            redirect_to friend_requests_path
        else
            flash[:alert] = "There was an error, friend request not sent."
            redirect_to friend_requests_path
        end      
    end

    def update
        @request = FriendRequest.find(params[:id])
        @request.status = true

        #if friendship created, automatically create private chat. (user_1 user_2 order doesnt matter)
        if @request.save
            Chat.create(user_1_id: @request.requester.id, user_2_id: @request.reciever.id)
        end
            
        redirect_to friend_requests_path
    end

    def destroy
        #either cancel friend request, or unfriend
        @request = FriendRequest.find(params[:id])
        @request.destroy
        
        redirect_to friend_requests_path 
    end

    private

    #returns 10 default users (users you can send request to)
    def default_users(limit)
        return current_user.can_send_request.limit(limit)
    end

    def friend_request_params
        params.permit(:reciever_id)
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_search.html.erb
<%@users.each do |user|%>
    <div class="d-flex bg-light m-2">
        <div class="square-frame">
            <img src="<%=asset_path(url_for(user.profile.attached_img))%>">
        </div>

        <div class="d-flex justify-content-between align-items-center w-100 m-2">
            <%=link_to "#{user.name}", user_profile_path(user), class: "profile-link text-center mr-2 "%> 

            <%friend_request_result = current_user.friend_request_with(user)%>
            
            <%if friend_request_result.count > 0 %>
                <%friend_request = friend_request_result.first%>

                <% if friend_request.status == true %>
                    <%=button_to "Unfriend", friend_request_path(friend_request),
                        method: :delete,
                        data: {confirm: "Are you sure? You will no longer be able to message this person."},
                        class: "btn btn-light btn-sm  border w-100"%>
                <%else%>
                    <%# either someone has sent an invite, or current_user is waiting on response.  %>
                    <% if friend_request.requester_id == current_user.id %>
                        <%=button_to "Cancel Invite", friend_request_path(friend_request), method: :delete, class: "btn btn-danger btn-sm rounded border w-100"%>
                    <% else %>
                        <div class="d-flex">
                            <%=button_to "Accept", friend_request_path(friend_request), method: :patch, class: "btn btn-primary btn-sm rounded border mx-2"%>
                            <%=button_to "Decline", friend_request_path(friend_request), method: :delete, class: "btn btn-light btn-sm rounded border"%>
                        </div>
                    <% end %>
                <%end%>
            <%else%>
                <%=button_to "Invite", friend_requests_path(reciever_id: user.id), method: :post, class: "btn btn-sm btn-light border rounded w-100"%>
            <%end%>
        </div>
    </div>
<%end%>

app/views/friend_requests/index.html.erb
<div class="w-100 d-flex justify-content-center">
    <div class="friend-requests w-100 mx-3">
        <div class="notfriend-column d-flex flex-column">

            <div class="new-users border rounded p-2 mb-4">
                <%= form_with url: "/friend_requests/search", method: :get, local: false, class: "d-flex mb-3" do |form| %>
                    <%= form.text_field :query, placeholder: "Search for users here...", class: "search-field border" %>
                    <%= form.submit "Search", class: "btn btn-light"%>
                <% end %>

                <p class="search-result-count text-secondary mx-1 mb-1"><%=@new_users.count%> results found.</p>

                <div class="new-users-container">
                    <%@new_users.each do |user|%>
                        <div class="d-flex align-items-center bg-light border m-1">
                            <div class="square-frame">
                                <img src="<%=asset_path(url_for(user.profile.attached_img))%>">
                            </div>
                            <div class="d-flex justify-content-between align-items-center w-100 m-2">
                                <%=link_to "#{user.name}", user_profile_path(user), class: "profile-link text-center mr-2"%> 
                                <%=button_to "Invite", friend_requests_path(reciever_id: user.id), method: :post, class: "btn btn-light btn-sm border rounded w-100"%>
                            </div>
                        </div>
                    <%end%>
                </div>
            </div>

            <div class="incoming-requests">
                <h4 class="p-2 d-inline-block">Incoming Requests</h4>
                <span class="badge bg-secondary"><%=@invites_from.count%></span>
                <%@invites_from.each do |user|%>
                    <div class="incoming-request d-flex justify-content-between align-items-center rounded bg-light my-2 p-2">
                        <%invite = FriendRequest.where(requester_id: user.id, reciever_id: current_user.id, status: false).first%>
                        <div class="user-info d-flex align-items-center">
                            <div class="square-frame">
                                <img class="" src="<%=asset_path(url_for(user.profile.attached_img))%>">
                            </div>
                            <div class="d-flex flex-column mx-3">
                                <%=link_to "#{user.name}", user_profile_path(user), class: "profile-link"%>
                                <%=link_to "View Profile", user_profile_url(user), class: "view-profile"%>
                            </div>
                        </div>

                        <div class="buttons-container d-flex">
                            <%=button_to "Accept", friend_request_path(invite), method: :patch, class: "btn-primary rounded border mx-2"%>
                            <%=button_to "Decline", friend_request_path(invite), method: :delete, class: "btn-light rounded border"%>
                        </div>
                    </div>
                <%end%>
            </div>

            <div class="sent-requests mt-2">
                <h4 class="p-2 d-inline-block">Sent Requests</h4>
                <span class="badge bg-secondary"><%=@pending_users.count%></span>

                <%@pending_users.each do |user|%>
                    <div class="sent-request d-flex justify-content-between bg-light rounded m-2 p-2">
                        <%invite = FriendRequest.where(requester_id: current_user.id, reciever_id: user.id, status: false).first%>
                        <div class="user-info">
                            <%=link_to "#{user.name}", user_profile_path(user), class: "profile-link"%>
                            <%=link_to "View Profile", user_profile_url(user), class: "view-profile"%>
                        </div>
                        <%=button_to "Cancel", friend_request_path(invite), method: :delete, class: "btn-danger rounded border"%>
                    </div>
                <%end%>
            </div>

            
        </div>

        <%# maybe make friend column into partial%>
        <%# friend col disappears at small size becaus einherit from wall_posts index %>

        <div class="d-flex flex-column">
            <div class="d-flex justify-content-between bg-light border shadow-sm p-2 mx-0 mb-1">
                <h4 class="d-inline-block m-0">Friends</h4>
                <span class="badge bg-secondary"><%=current_user.friends.count%></span>
            </div>

            <% if current_user.friends.count == 0 %>
                <p class="text-secondary p-2">
                    Looks like you don't have any friends yet. Make some friends by sending invites to other users!
                </p>
            <%end%>
            <%current_user.friends.each do |friend|%>
                <div class="friend-card bg-white d-flex p-2 my-1">

                    <%friendship = current_user.friendship(friend)%>

                    <div class="square-frame">
                        <img class="profile-pic" src="<%=asset_path(url_for(friend.profile.attached_img))%>">
                    </div>
                    <div class="info d-flex flex-column justify-content-center w-100 ms-2">
                        <%=link_to "#{friend.name}", user_profile_path(friend), class: "profile-link"%>
                        <div class="d-flex align-items-end justify-content-between">
                            <%=button_to "Unfriend", friend_request_path(friendship),
                                method: :delete,
                                data: {confirm: "Are you sure? You will no longer be able to message this person."},
                                class: "btn btn-sm btn-light border p-1"
                            %>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/friend_requests/search.js.erb
document.getElementsByClassName("new-users-container")[0].innerHTML = `
    <%= escape_javascript(render partial: 'friend_requests/search')%>     
`;

document.getElementsByClassName("search-result-count")[0].textContent = `
    <%= escape_javascript("#{@users.count}" + " results found.")%>
`