config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  
  devise_for :users,controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "walls/posts#index"

  resources :messages

  resources :clubs do
    resources :posts, module: :clubs do
      resources :comments, only: [:new, :create, :destroy]
    end
    resource :chatroom, as: "chat"
  end

  resource :wall do 
    resources :posts, module: :walls do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :memberships, only: [:create, :update, :destroy]

  #where does users index go?
  resources :users, only: [:edit, :update] do
    resource :profile, only: [:show, :edit, :update]
  end

  resources :chats, only: [:index, :show]

  resources :friend_requests, only: [:new, :create, :index, :destroy, :update]
  get "/friend_requests/search", to: "friend_requests#search", as: "search_users"

  #Like and unlike paths
  post "/posts/:id/like", to: "posts#like", as: "like_post" 
  delete "/posts/:id/like", to: "posts#unlike", as: "unlike_post"

  post "/posts/:post_id/comments/:id/like", to: "comments#like", as: "like_comment"
  delete "/posts/:post_id/comments/:id/like", to: "comments#unlike", as: "unlike_comment"

  resources :notifications, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    
    include ActiveModel::Validations
    validates_with ImageValidator

    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true, length: {minimum: 10}

    belongs_to :user
    #make post polymorphic! (can belong to either wall or club)
    belongs_to :postable, polymorphic: true

    has_one_attached :image

    has_many :comments, dependent: :destroy
    has_many :likes, :as => :likeable, dependent: :destroy

    #make sure a user can only like ONCE on a post
    def liked?(user)
        self.likes.find{|like| like.user_id == user.id}
    end

    def date
        self.created_at.strftime("%d-%m-%Y %H:%M")
    end
end

app/controllers/clubs/posts_controller.rb
class Clubs::PostsController < PostsController
    #make sure later that check member ALWAYS runs before check_blocked, or it will error why does prepend_before_action result error?
    before_action :check_member 
    before_action :check_blocked

    def index
        #maybe all posts, from UNBLOCEKD USERS only?
        @club = Club.find(params[:club_id])
        @posts = Post.where(postable_type: "Club", postable_id: params[:club_id]).order('created_at DESC')
    end

    private

    def check_blocked
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if (@membership.blocked == true)
            #add flash[:error] to club show page later
            flash[:alert] = "You are blocked from this club."
            redirect_to club_path(@membership.club_id)
        end
    end

    def check_member
        @membership = Membership.find_by(member_id: current_user.id, club_id: @postable.id)
        if @membership.nil?
            flash[:alert] = "You must be a member of this club"
            redirect_to @postable
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    prepend_before_action :load_postable, except: [:like, :unlike]
    prepend_before_action :load_postable_for_like, only: [:like, :unlike]

    before_action :require_owner, only: [:edit, :update, :destroy]
    
    def show
        @post = Post.find(params[:id])
        #generate new comment obj, for "new comment form" in post#show
        @comment = @post.comments.new


        #adjust club template to use show_owned and unowned template. 
        if @post.user == current_user
            render :show_owned
        else
            render :show_unowned
        end
    end

    def new
        @post = @postable.posts.new
    end

    def create
        @post = @postable.posts.build(post_params)
        @post.user = current_user

        if @post.save
            flash[:alert] = "Post successfully created."
            redirect_to [@postable_name, :posts]
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            flash[:alert] = "Post succesfully saved."
            redirect_to [@postable_name, @post]
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.image.purge
        @post.destroy

        redirect_to [@postable_name, :posts]
    end

    def like
        Like.create(user_id: current_user.id, likeable_id: @post.id, likeable_type: "Post")
        redirect_to [@postable_name, @post]
    end

    def unlike  
        Like.find_by(likeable_id: @post.id, user_id: current_user.id, likeable_type: "Post").destroy
        redirect_to [@postable_name, @post]
    end

    protected

    def post_params
        params.require(:post).permit(:title, :body, :image)
    end

    def load_postable
        resource, id = request.path.split("/")[1,2]
        @postable = resource.singularize.classify.constantize.find(id)
        #specifically for routes.
        @postable_name = @postable
    end

    def load_postable_for_like
        #singular (ONLY wall/posts) and plural (clubs/1/posts) routes handled here, because all types of post likes will route to post#like
        @post = Post.find(params[:id])
        @postable = @post.postable_type.classify.constantize.find(@post.postable_id)
        @postable_name = (@postable.class == Wall)? "wall" : @postable 
    end

    def require_owner
        @post = Post.find(params[:id])
        unless (current_user.id == @post.user_id)
            #make into flash[:error] later
            flash[:alert] = "You do not have the permission to edit this post"
            redirect_to [@postable_name, @post]
        end
    end
end

app/controllers/walls/posts_controller.rb
class Walls::PostsController < PostsController
    #overwrite @postable
    prepend_before_action :load_postable

    def index
        @posts = Post.where(postable_type: "Wall").order("created_at DESC")
    end

    private

    def load_postable
        @postable = Wall.first
        @postable_name = "wall"
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
|<%=form_with model: comment do |form|%>
    <%=form.label :comment%><br>
    <%=form.text_field :body%>

    <%=form.hidden_field :post_id, value: @post.id%>

    <br>
    <%=form.submit%>
<%end%>

app/views/posts/_post_form.html.erb
<%=form_with model: [@postable, @post] do |form|%>
    <div class="form-container p-3 my-4 bg-light">

        <h3><%=form_title%></h3>

        <div class="post-errors">
            <%unless @post.errors.messages.empty?%>
                <div class="alert alert-danger">
                    <%@post.errors.full_messages.each do |msg|%>
                        <li><%=msg%></li>
                    <%end%>
                </div>
            <%end%>
        </div>

        <div class="form-group my-2">
            <%=form.label :title%>
            <%=form.text_field :title, class: "form-control"%>
        </div>

        <div class="form-group my-2">
            <%=form.label :body%>
            <%=form.text_area :body, class: "form-control body"%>
        </div>

        <div class="form-group my-2">
            <%=form.label :image%>
            <%=form.file_field :image, class: "file-field form-control", direct_upload: true%>
            <small class="form-text text-muted">(Optional)</small>
        </div>

        <%=form.submit "Submit", class:"submit-button p-2 mt-3 w-100 border text-white"%>
    </div>
<%end%>

app/views/posts/_show_partial.html.erb
<%# not used currently %>

app/views/posts/show.html.erb
<div id="post-container" class="d-flex justify-content-center">
    <div id="post" class="bg-light d-flex flex-column mt-5 p-3">
        <h1><%=@post.title%></h1>

        <%if @post.image.attached?%>
            <img class="post-img" src="<%=url_for(@post.image)%>">
        <%end%>

        <div>
            <%=@post.body%>
            <p>Likes: <%=@post.likes.count%></p>
        </div>

        <%if current_user.id == @post.user_id%>
            <div class="links">
                <%=link_to "Edit", edit_post_path(@post)%>
                <%=link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
        <%else%>
            <%if @post.liked?(current_user) %>
                <%=button_to "Unlike", unlike_post_path, method: :delete %>
            <%else%>
                <%=button_to "Like", like_post_path, method: :post%>
            <%end%>
        <%end%>

        <%=render "comment_form", comment: @comment %>
        <%# 
        check if post is deleted, likes on comments deleted aswell %>
        <div class="comments mt-5">
            <%@post.comments.each do |comment|%>
                <div class="comment py-2 border-bottom">
                    <b><%=comment.user.name%> </b>
                    <i><%=comment.date%></i>
                    <p>Likes: <%=comment.likes.count%></p>
                    <%=comment.body%>
                    <br>
                    <%if current_user.id == comment.user_id%>
                        <%=link_to "Delete", comment_path(comment), method: :delete,data: {confirm: "Are you sure?"}%>
                    <%else%>
                        <%if comment.liked?(current_user) %>
                            <%=button_to "Unlike", unlike_comment_path(id: @post.id, comment_id: comment.id), method: :delete %>
                        <%else%>
                            <%=button_to "Like", like_comment_path(id: @post.id, comment_id: comment.id), method: :post%>
                        <%end%>
                    <%end%>
                </div>
            <%end%>
        </div>
    </div>
</div>